name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    tags:
      - "*-*"
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"

      - name: Print changed files
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: Cache toolchains
        uses: actions/cache@v1
        with:
          path: toolchains
          key: toolchains-v1

      - name: Build
        # if: steps.getfile.outputs.files == 'spk/*'
        env:
          FILES: ${{ steps.getfile.outputs.files }}
        uses: docker://synocommunity/spksrc:latest
        with:
          entrypoint: ./.github/actions/build-push-pr.sh
          # args: arch-x64-6.1
          args: all-supported

      - name: List packages
        run: ls packages

  release-build:
    name: Build Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache toolchains
        uses: actions/cache@v1
        with:
          path: toolchains
          key: toolchains-v1

      - name: Build
        uses: docker://synocommunity/spksrc:latest
        with:
          entrypoint: ./.github/actions/build-tag.sh
          # args: arch-x64-6.1
          args: all-archs-latest
      - name: List packages
        run: ls packages

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v2-preview
      #   with:
      #     name: Packages
      #     path: packages/*.spk

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*.spk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
